import ReduxProvider from '@/redux/ReduxProvider';
import './globals.css';
import localFont from 'next/font/local';

const myFont = localFont({ src: '../public/fonts/Satoshi-Variable.woff2' });

export const metadata = {
  title: 'Eminence Wallet',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
