import "../globals.css";

export const metadata = {
  title: "Eminence : Forget Password",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <>{children}</>;
}
